hw3: mystring.h File Reference
mystring.h File Reference
#include <stdlib.h>
#include <string.h>
Functions
char * mystrdup (const char *src)
char * mystrndup (const char *s, size_t n)
Carries out a deep copy operation on a string into a new memory block. Keep the original whole. Give a pointer to the new memory block that the copied string is stored in.
size_t mystrlen (const char *s)
char * mystrcpy (char *dst, const char *src)
char * mystrncpy (char *destination, const char *source, size_t num)
char * mystrncat (char *destination, const char *source, size_t num)
char * mystrcat (char *destination, const char *source)
Function Documentation
mystrcat()
char* mystrcat (char * destination, const char * source)
@purpose Join two strings together. The characters from the source are appended to those at the destination, and a null-terminator is added at the end.
Parameters
destination The place when the concatenation will end.
source The additional source for the intention.
Returns
A pointer to the destination.
mystrcpy()
char* mystrcpy (char * dst, const char * src)
@purpose One string to another by copying.
Parameters
dst The string that will be used. The source will replace this with its own data.
src The original string.
Returns
The destination string (pointer).
Referenced by main(), make_user(), and mystrdup().
mystrdup()
char* mystrdup (const char * src)
mystring.h
Author
Alexander Lap
mystring.c
Author
Alexander Lap Make a character string double.
Parameters
src String is duplicated.
Returns
Pointer to an empty block of memory that has just been allocated, into which the original string has been duplicated. This block can be freed with the free() method after it is no longer required. If memory cannot be allocated, it returns null.
References mystrcpy(), and mystrlen().
Referenced by main().
mystrlen()
size_t mystrlen (const char * s)
@purpose Discover the length of a string with a nul termination.
Parameters
s The size of the string.
Returns
The length of the string
Referenced by main(), make_random_student(), make_student(), and mystrdup().
mystrncat()
char* mystrncat (char * destination, const char * source, size_t num)
@purpose Add the first n characters of the source string to the end of the destination string when you concatenate two strings. Additionally, the target string will have a null terminator added.
Parameters
destination Where the concatenation will end up.
source To the end of the destination, put the source.
num How many character should be added.
Returns
A pointer in the right direction.
Referenced by main().
mystrncpy()
char* mystrncpy (char * destination, const char * source, size_t num)
@purpose Copies a string from one place to another while having a cap on the number of characters that can be copied. This prevents copying a string from going off the stack and overwriting data that is already in memory.
Parameters
destination The target string.
source The origial string.
num How many characters to copy.
Returns
A pointer to the destination.
Referenced by main(), and mystrndup().
mystrndup()
char* mystrndup (const char * s, size_t n)
Carries out a deep copy operation on a string into a new memory block. Keep the original whole. Give a pointer to the new memory block that the copied string is stored in.
Parameters
s There is a duplicate string.
n How many characers you should copy.
Returns
A pointer to the deep copied string.
References mystrncpy().
Referenced by main(), make_random_student(), and make_student().