hw3: rand_func.h File Reference
rand_func.h File Reference
Functions
int randInt ()
int randCharInt ()
char * randFill ()
Function Documentation
randCharInt()
int randCharInt ()
Generates pseudo-random integers within the range of uppercase ASCII chars. Generator is seeded in randFill, in order to produce more random integers.
Returns
letter The randomly generated integer for uppercase ASCII chars.
randFill()
char* randFill ()
Takes in an array, the size of the array, and a specified maximum, and fills the array with randomly generated integers, produced by randInt function. When the array is full, the array is printed, then sorted, then printed again.
Parameters
r Array to be filled with random integers.
array_size The defined size of the array.
max The specified maximum value in the random generator's range.
Returns
a The character array filled with random chars.
References ARR_MAX, and randCharInt().
Referenced by rand_struct().
randInt()
int randInt ()
Generates pseudo-random integers within the range specified.
Returns
value The random integer generated.
References INT_MAX.
Referenced by rand_struct().