hw3: structhelper.h File Reference
structhelper.h File Reference
#include <stdint.h>
#include "mystring.h"
#include <stdio.h>
Data Structures
struct Student
Functions
Student * make_student (char *name, int grade, float gpa)
void print_student (Student *s)
Student * make_random_student ()
char * make_random_string (size_t length)
char get_random_char ()
int get_random_int_range (int min, int max)
Student ** make_random_student_n (size_t n)
void print_student_n (Student **s_arr, size_t count)
Student ** student_arr_dup (Student **source, size_t count)
void free_student_arr (Student **s_arr, size_t count)
Student ** deep_copy_student_arr (Student **s_arr, size_t count)
Function Documentation
deep_copy_student_arr()
Student** deep_copy_student_arr (Student ** s_arr, size_t count)
@purpose Creates a deep copy of a student structure array. Instead of just linking the new struct to the pointers already allocated in the old one, this copies the original struct.
Parameters
s_arr The variety of students to copy.
count How many items there are in the student array.
Returns
A pointer to the copied array.
References make_student().
Referenced by main().
free_student_arr()
void free_student_arr (Student ** s_arr, size_t count)
@purpose Give the related pointers a free pass before changing them to null to release an array of pupils. This transfers memory from the array back to the slack.
Parameters
s_arr The array to free.
count The array's size in terms of items.
Referenced by main().
get_random_char()
char get_random_char ()
@purpose Choose a random letter from A to Z.
Returns
The random character.
Referenced by make_random_string().
get_random_int_range()
int get_random_int_range (int min, int max)
@purpose The range of random integers.
Parameters
min The lowest end of the range
max The higest point in the range.
Returns
The random number.
Referenced by make_random_student().
make_random_string()
char* make_random_string (size_t length)
@purpose Obtains a random string of the desired length. Returns a string that only contains the uppercase letters A through Z.
Parameters
length The random string's length.
Returns
A pointer to the random string.
References get_random_char().
Referenced by make_random_student().
make_random_student()
Student* make_random_student ()
@purpose Makes a student with random data in it.
Returns
A student structure contained data created at random.
References get_random_int_range(), Student::gpa, Student::grade, make_random_string(), mystrlen(), mystrndup(), and Student::name.
Referenced by main(), and make_random_student_n().
make_random_student_n()
Student** make_random_student_n (size_t n)
@purpose Create a random student array of the specified size.
Parameters
n The quantity of students chosen at random.
Returns
A pointer to the array of random students.
References make_random_student().
Referenced by main().
make_student()
Student* make_student (char * name, int grade, float gpa)
@purpose Create a student using the data provided.
Parameters
name Name of student.
grade Grade of student.
gpa GPA of student.
Returns
A pointer to newly created student.
References Student::gpa, Student::grade, mystrlen(), mystrndup(), and Student::name.
Referenced by deep_copy_student_arr(), and main().
print_student()
void print_student (Student * s)
@purpose Student struct is printed.
Parameters
s A pointer to a student struct.
References Student::gpa, Student::grade, and Student::name.
Referenced by main(), and print_student_n().
print_student_n()
void print_student_n (Student ** s_arr, size_t count)
@purpose A variety of students is printed.
Parameters
s_arr Prints the array
count How many students are in the array.
References print_student().
Referenced by main().
student_arr_dup()
Student** student_arr_dup (Student ** source, size_t count)
@purpose A variety of kids shallow copy.
Parameters
source The origin array.
count A tally of the array's component.
Returns
The copied array.
Referenced by main().