hw3: user.c File Reference
user.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "user.h"
#include "rand_funcs.h"
Functions
User * make_user (char *username, int join_year, int num_posts)
void print_struct (User *user)
User * rand_struct ()
User ** count_array (int count)
void print_array (User **uArr, int count)
User ** dup_array (User **dupArr, int count)
void free_array (User **freeArr, int count)
Function Documentation
count_array()
User** count_array (int count)
Takes a count value and allocates an array that can hold that many pointers to the struct of type User. Fills each element of the array with a pointer to a new, randomly generated struct.
Parameters
count The number of pointers to User struct that the array will hold.
Returns
u1 The array of pointers to struct of type User.
References rand_struct().
dup_array()
User** dup_array (User ** dupArr, int count)
Duplicates an array fo pointers to struct of type User. Must determine the # of elements in the array, and size of ememory to be allocated.
Parameters
dupArr The array of pointers to struct to be duplicated.
num_ele The amount of pointers in the array being duplicated.
free_array()
void free_array (User ** freeArr, int count)
Takes an array of pointers to struct of type User and de-allocates (frees) all the structs pointed to.
Parameters
freeArr The array of pointers to struct to be freed.
make_user()
User* make_user (char * username, int join_year, int num_posts)
Allocates a struct of type User and fills its fields with data passed in as parameters.
Parameters
username The username of the user.
join_year The year in which the user joined.
num_posts The number of posts the user has made.
Returns
new_u The newly created user struct.
References User::join_year, mystrcpy(), User::num_posts, and User::username.
Referenced by rand_struct().
print_array()
void print_array (User ** uArr, int count)
Takes an array of pointers and a count value and prints out all the structs pointed to in the array.
Parameters
uArr The array of pointers to struct of type User.
References print_struct().
print_struct()
void print_struct (User * user)
Prints a struct passed to the function.
Parameters
user The struct to be printed.
References User::join_year, User::num_posts, and User::username.
Referenced by print_array().
rand_struct()
User* rand_struct ()
Creates a struct of type User and fills the struct with random data. A random string, and two random integers are generated in order to fill the struct. The struct is then returned.
Parameters
username The randomly generated char array for the username.
year The randomly generated integer for the join year.
posts The randomly generated integer for the post count.
Returns
rand_struct The User struct filled with random data.
References make_user(), randFill(), and randInt().
Referenced by count_array().